import { imagesForCategory } from './images.js';

export const DEFAULT_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Tamil Traditional Paruppu Podi (Lentil Powder)',
    description: 'An authentic South Indian household specialty. Hand-roasted Toor Dal, Bengal Gram, pepper, and dry red chillies stone-milled to sandy-perfection and laced with high-purity garlic-free asafoetida (Hing). Mix with steaming rice and A2 Ghee.',
    price: 95,
    costPrice: 40,
    category: 'Podi Varieties',
    images: imagesForCategory('Podi Varieties', 0),
    enabled: true,
    stock: 150,
    traditionalBenefit: 'Supplies complete high plant protein, improves appetite, and stimulates healthy agni (digestive fire).',
    weight: '150g',
    ingredients: ['Toor Dal (Pigeon Peas)', 'Bengal Gram (Chana Dal)', 'Black Pepper', 'Dry Red Chillies', 'Vedic Asafoetida', 'Unrefined Rock Salt']
  },
  {
    id: 'prod-2',
    name: 'Organic Karuveppilai (Curry Leaves) Rice Podi',
    description: 'Made from premium, iron-rich fresh curry leaves sourced from regional organic fields. Sun-dried carefully and dry-milled under strict temperature controls with black pepper, urad dal, and dry red chili to preserve its natural therapeutic essence.',
    price: 110,
    costPrice: 45,
    category: 'Podi Varieties',
    images: imagesForCategory('Podi Varieties', 1),
    enabled: true,
    stock: 120,
    traditionalBenefit: 'Rich in dietary iron and Vitamin A. Exceptional for hair growth, liver detoxification, and skin radiance.',
    weight: '150g',
    ingredients: ['Fresh Organic Curry Leaves', 'Black Gram (Urad Dal)', 'Whole Red Chilies', 'Black Pepper', 'Asafoetida', 'Sea Salt']
  },
  {
    id: 'prod-3',
    name: 'Traditional Idli Milagai Podi (Gunpowder)',
    description: 'The definitive South Indian accompaniment for soft idlis and crispy dosas. Created with choice dual lentil dry-roasting, black sesame seeds, and hot Guntur chilies crushed coarsely to retain that traditional rustic bite.',
    price: 90,
    costPrice: 35,
    category: 'Podi Varieties',
    images: imagesForCategory('Podi Varieties', 2),
    enabled: true,
    stock: 180,
    traditionalBenefit: 'Boosts blood circulation, warms the throat, and delivers rich dietary fibers.',
    weight: '150g',
    ingredients: ['Urad Dal', 'Bengal Gram', 'Guntur Red Chili', 'Stone-Ground Black Sesame Seeds', 'Pure Hing', 'Hygienic Sea Salt']
  },
  {
    id: 'prod-4',
    name: 'Madurai Special Maavadu (Baby Mango) Pickle',
    description: 'Our crown jewel. Tender baby mangoes hand-harvested during early morning dew, salted in heavy clay jars (Bharani) for several weeks, and cured in cold-pressed sesame oil, mustard dust, and hot red chili powder. A timeless memory.',
    price: 195,
    costPrice: 85,
    category: 'Pickle Varieties',
    images: imagesForCategory('Pickle Varieties', 0),
    enabled: true,
    stock: 90,
    traditionalBenefit: 'Stimulates digestive saliva, aids sluggish morning digests, and pairs exceptionally with cool curd rice.',
    weight: '300g',
    ingredients: ['Tender Baby Mangoes', 'Cold-Pressed Sesame Oil (Gingelly)', 'Red Chili Powder', 'Coarse Mustard Yellow Powder', 'Asafoetida', 'Sea Salt']
  },
  {
    id: 'prod-5',
    name: 'Traditional Citron (Narthangai) Pickle',
    description: 'Heritage dietary cure. Tender local Citron rind carefully sliced, naturally brined, and sun-matured. Cooked in pure unrefined sesame oil with fenugreek spice layers. No vinegar, zero coloring chemical additions.',
    price: 145,
    costPrice: 60,
    category: 'Pickle Varieties',
    images: imagesForCategory('Pickle Varieties', 1),
    enabled: true,
    stock: 110,
    traditionalBenefit: 'Extremely popular for soothing pitta-related issues, overcoming morning sickness, and aiding liver bile production.',
    weight: '250g',
    ingredients: ['Fresh Native Citron (Narthangai)', 'Cold-Pressed Sesame Oil', 'Red Pepper Dust', 'Dry Fenugreek Powder', 'Hing', 'Sea Salt']
  },
  {
    id: 'prod-6',
    name: 'Mulaikattiya Sathu Maavu (Sprouted Multi-Grain Mix)',
    description: 'A traditional whole-family nutrition powder. Over 10 grains and legumes including Finger Millet, Pearl Millet, Sorghum, and Red Rice are sprouted, solar-dehydrated, gently hand-roasted, and stone-milled with aroma-rich dry ginger and green cardamom.',
    price: 240,
    costPrice: 110,
    category: 'Porridge Mix',
    images: imagesForCategory('Porridge Mix', 0),
    enabled: true,
    stock: 85,
    traditionalBenefit: 'High dietary fibers, natural complex carbs, calcium, and minerals. Excellent breakfast substitute for all ages.',
    weight: '500g',
    ingredients: ['Sprouted Finger Millet (Ragi)', 'Sprouted Pearl Millet (Kambhu)', 'Sorghum (Cholam)', 'Mapillai Samba Red Rice', 'Moong Dal', 'Dry Ginger', 'Cardamom']
  },
  {
    id: 'prod-7',
    name: 'Kovil Puliyodharai Mix (Traditional Tamarind Paste)',
    description: 'Recreate the rich, divine taste of Srirangam temple tamarind rice at home. Prepared using concentrated, thick ripe tamarind extract slow-boiled in pure wood-pressed sesame oil with roasted black sesame seeds, peanuts, and freshly ground secret temple spices.',
    price: 165,
    costPrice: 75,
    category: 'Instant Mix',
    images: imagesForCategory('Instant Mix', 0),
    enabled: true,
    stock: 130,
    traditionalBenefit: 'Balances kapha and vata, stimulates stomach juices, and serves as an ideal travel food with a long shelf life.',
    weight: '250g',
    ingredients: ['Pure Tamarind Extract', 'Wood-Pressed Sesame Oil', 'Peanuts', 'Roasted Fenugreek Powder', 'Mustard Seeds', 'Dry Red Chilies', 'Curry Leaves']
  },
  {
    id: 'prod-8',
    name: 'Traditional Sambar Powder (Madurai Grandma Recipe)',
    description: 'An ancient recipe handed down generations. Sourced from organic farm clusters, dry-roasted under early morning sun rays, and dry-ground in native stone mills to preserve its deep aromatic terpene oils.',
    price: 140,
    costPrice: 55,
    category: 'Instant Mix',
    images: imagesForCategory('Instant Mix', 1),
    enabled: true,
    stock: 140,
    traditionalBenefit: 'Supplies natural anti-inflammatory curcumin, improves intestinal gut microbial flora.',
    weight: '250g',
    ingredients: ['Byadgi Red Chili', 'Coriander Seeds', 'Fenugreek (Methi)', 'Toor Dal', 'Curry Leaves', 'Turmeric Roots']
  },
  {
    id: 'prod-9',
    name: 'Hygienic Sundakkai Vathal (Salt Cured Turkey Berry)',
    description: 'Carefully chosen organic Turkey Berries brined in fresh sour buttermilk, salted cleanly, and dried hygienically inside solar houses to protect against street dust and pests. Deep fry in hot oil to make a perfect crunchy rice side.',
    price: 85,
    costPrice: 35,
    category: 'Vathal Varieties',
    images: imagesForCategory('Vathal Varieties', 0),
    enabled: true,
    stock: 220,
    traditionalBenefit: 'Highly effective in eliminating stomach worms, improves iron counts, and regulates high blood pressure.',
    weight: '100g',
    ingredients: ['Fresh Turkey Berries (Sundakkai)', 'Unrefined Sea Salt', 'Sour Spiced Buttermilk']
  },
  {
    id: 'prod-10',
    name: 'Hygienic Manathakkali Vathal (Black Nightshade Berries)',
    description: 'Savoury, slightly bitter dried medical berries. Cured carefully in low-fat salted yogurt and sun-dried until dry-crisp. Toss in hot ghee or sesame oil and mix with rice or add to appetizing Vatha Kuzhambu.',
    price: 85,
    costPrice: 35,
    category: 'Vathal Varieties',
    images: imagesForCategory('Vathal Varieties', 1),
    enabled: true,
    stock: 190,
    traditionalBenefit: 'Highly recognized in Ayurveda for healing mouth & stomach ulcers, cooling body heat, and improving eye health.',
    weight: '100g',
    ingredients: ['Black Nightshade Berries (Manathakkali)', 'Pure Yogurt', 'Sea Salt']
  }
];
